name: Generate Wavy Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'  # প্রতি দিন রাত 12 টায় রান হবে
  workflow_dispatch:  # ম্যানুয়ালি রান করার অপশন

permissions:
  contents: write  # Permission দিতে হবে

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Waves
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            wavy.svg
          
      - name: Push Generated Wave
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add wavy.svg || echo "No changes to commit"
          git commit -m "Updated Wavy Contribution Graph" || echo "No new changes"
          git push || echo "No changes to push"
